version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "angularjs",
    "react",
    "vue",
    "ember",
    "meteor",
    "angular"
  ]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"

[[transformers]]
name = "prettier"
enabled = true